name: bntu_schedule
description:
  'The mobile part of the application for viewing the schedule of couples at the
  BNTU University.'
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_app_check: ^0.2.1+8
  firebase_core: ^2.24.2
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  talker_flutter: ^3.6.0
  talker_logger: ^3.1.0
  go_router: ^13.1.0
  firebase_crashlytics: ^3.4.14
  firebase_analytics: ^10.8.5
  firebase_performance: ^0.9.3+13
  flutter_platform_widgets: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7

flutter_launcher_icons:
  image_path: 'assets/images/svg/app_logo.svg'
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#ffffff'

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          style: normal

    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          style: normal
  assets:
    - .env
