name: bntu_schedule
description:
  'The mobile part of the application for viewing the schedule of couples at the
  BNTU University.'
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  talker_flutter: ^3.6.0
  talker_logger: ^3.1.0
  talker_dio_logger: ^2.4.0
  talker_bloc_logger: ^2.4.0
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  get_it: ^7.6.4
  equatable: ^2.0.5
  week_of_year: ^2.2.0
  firebase_core: ^2.24.2
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_app_check: ^0.2.1+8
  dartz: 0.10.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2

flutter_launcher_icons:
  image_path: 'assets/images/app_logo.png'
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#ffffff'

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          style: normal
  assets:
    - .env

flutter_intl:
  enabled: true
